In [3]:
%pip install numpy

  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## Basic Array

In [7]:
np_arr = np.array([1,2,3])
np_arr

array([1, 2, 3])

In [11]:
list_arr = [1,2,3.5, "a"]
np_arr = np.array([1,2,3.5, "b"])

print("Allow Multiple Types", list_arr)
print("Allow/Converts to single Types -", np_arr) #we can see its converted to string

Allow Multiple Types [1, 2, 3.5, 'a']
Allow/Converts to single Types - ['1' '2' '3.5' 'b']


In [12]:
py_arr = [[1,2,3], [4,5,6], [7,8,9]]
print("py_arr", py_arr)

np_arr = np.array(py_arr)
print("np_arr", np_arr)


py_arr [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_arr [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Generation Functions

In [17]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [18]:
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## Random Generation function

In [22]:
np.random.rand(10) # normalization 0-1 are value

array([0.64684775, 0.40109847, 0.05288446, 0.54970897, 0.96786082,
       0.66439256, 0.37620279, 0.15338057, 0.69363284, 0.29955694])

In [24]:
np.random.randn(10) # contains negative number , standaraization -3 3 all value

array([-0.90820889,  2.01033791,  0.88670446,  0.0734806 , -0.58356058,
       -0.27349654,  0.21511322,  0.18835945, -0.11871289, -0.80449444])

In [25]:
np.random.randint(10,20,10)

array([18, 17, 13, 10, 14, 10, 13, 16, 11, 11], dtype=int32)

## Array Attributes

In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

## Array Methods

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.min()

np.int64(1)

In [34]:
print(arr.max())

9


In [33]:
print(arr.sum())

45


In [35]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [36]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [37]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
print(arr.argmin())

0


## Reshaping and resizing

In [41]:
arr = np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
arr = arr.reshape(6,5) # directly updated the orignional array called as resize
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## INDEXING AND SLICING OF VECTORS

In [45]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
arr[1:5]


array([12, 13, 14, 15])

In [48]:
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [53]:
arr[:4]

array([11, 12, 13, 14])

In [54]:
arr[3::2]

array([14, 16, 18, 20])

## INDEXING AND SLICING OF MATRIX

In [55]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [60]:
arr[3:6, 2:]

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [62]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [63]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [65]:
arr_positive_index = arr[bool_index]
arr_positive_index

array([12, 14, 16, 18, 20])